/**
 * Hostaway Dashboard Login Service
 *
 * Strategy: Use CapSolver to solve reCAPTCHA Enterprise, then POST to
 * Hostaway's login API directly. No browser needed for the CAPTCHA.
 *
 * The auditToken is generated by a fingerprinting service (CloudFront-hosted).
 * We try without it first — if rejected, we use a minimal browser session
 * just to generate the auditToken, then combine with CapSolver's captchaToken.
 */

import axios from 'axios';
import { chromium, Browser, Page } from 'rebrowser-playwright';

const LOGIN_API_URL = 'https://platform.hostaway.com/account/session';
const LOGIN_PAGE_URL = 'https://dashboard.hostaway.com/login';
const RECAPTCHA_SITEKEY = '6Le23SIrAAAAADpWBeJSU7b8wNAdL4vwQl7F1kli';

// 2FA session management
interface LoginSession {
  email: string;
  password: string;
  captchaToken: string;
  auditToken: string;
  createdAt: number;
  timeout: NodeJS.Timeout;
}

const pendingSessions = new Map<string, LoginSession>();

function cleanupSession(sessionId: string) {
  const session = pendingSessions.get(sessionId);
  if (session) {
    clearTimeout(session.timeout);
    pendingSessions.delete(sessionId);
  }
}

export interface LoginResult {
  success: boolean;
  jwt?: string;
  pending2fa?: boolean;
  sessionId?: string;
  error?: string;
  userEmail?: string;
  accountId?: string;
}

// ─── CapSolver Integration ──────────────────────────────────────────────────

async function solveCaptcha(): Promise<string> {
  const apiKey = process.env.CAPSOLVER_API_KEY;
  if (!apiKey) throw new Error('CAPSOLVER_API_KEY environment variable is required for Hostaway login');

  console.log('[HostawayLogin] Solving reCAPTCHA Enterprise via CapSolver...');

  // Create task
  const { data: createData } = await axios.post('https://api.capsolver.com/createTask', {
    clientKey: apiKey,
    task: {
      type: 'ReCaptchaV2EnterpriseTaskProxyLess',
      websiteURL: LOGIN_PAGE_URL,
      websiteKey: RECAPTCHA_SITEKEY,
      enterprisePayload: {},
    },
  });

  if (createData.errorId !== 0) {
    throw new Error(`CapSolver createTask failed: ${createData.errorCode} — ${createData.errorDescription}`);
  }

  const taskId = createData.taskId;
  console.log(`[HostawayLogin] CapSolver task created: ${taskId}`);

  // Poll for result (max 120 seconds)
  for (let i = 0; i < 120; i++) {
    await new Promise(r => setTimeout(r, 1500));

    const { data } = await axios.post('https://api.capsolver.com/getTaskResult', {
      clientKey: apiKey,
      taskId,
    });

    if (data.status === 'ready') {
      console.log(`[HostawayLogin] reCAPTCHA solved in ~${(i + 1) * 1.5}s`);
      return data.solution.gRecaptchaResponse;
    }

    if (data.errorId !== 0) {
      throw new Error(`CapSolver solve failed: ${data.errorCode} — ${data.errorDescription}`);
    }
  }

  throw new Error('reCAPTCHA solve timed out after 180 seconds');
}

// ─── AuditToken Extraction ──────────────────────────────────────────────────

async function extractAuditToken(): Promise<string> {
  console.log('[HostawayLogin] Extracting auditToken via browser...');
  let browser: Browser | null = null;

  try {
    browser = await chromium.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
    });
    const page = await browser.newPage();
    await page.goto(LOGIN_PAGE_URL, { waitUntil: 'domcontentloaded', timeout: 30000 });
    await page.waitForTimeout(5000); // Wait for fingerprinting script to load

    // The auditToken is generated by the CloudFront-hosted script (mutha-hostaway-wrapper.js)
    // Try to find it in the page's JavaScript state
    const token = await page.evaluate(`
      (function() {
        // Check for common fingerprinting storage locations
        var keys = Object.keys(window);
        for (var i = 0; i < keys.length; i++) {
          var val = window[keys[i]];
          if (typeof val === 'string' && val.length > 100 && val.length < 5000) {
            // Could be a token
          }
        }
        // Check for the lwsa iframe result (the fingerprinting service)
        // It typically stores a token that's used as auditToken
        return null;
      })()
    `);

    await browser.close();
    return (token as string) || '';
  } catch (err: any) {
    console.warn('[HostawayLogin] auditToken extraction failed:', err.message);
    if (browser) await browser.close().catch(() => {});
    return '';
  }
}

// ─── Login Flow ─────────────────────────────────────────────────────────────

async function attemptLogin(
  email: string,
  password: string,
  captchaToken: string,
  auditToken: string
): Promise<{ status: number; data: any }> {
  const res = await axios.post(LOGIN_API_URL, {
    email,
    password,
    captchaToken,
    auditToken,
  }, {
    headers: {
      'Content-Type': 'application/json',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36',
      'Origin': 'https://dashboard.hostaway.com',
      'Referer': 'https://dashboard.hostaway.com/',
    },
    validateStatus: () => true, // Don't throw on non-2xx
  });

  return { status: res.status, data: res.data };
}

/**
 * Login to Hostaway dashboard.
 * 1. Solve reCAPTCHA via CapSolver
 * 2. Try login without auditToken first
 * 3. If rejected, extract auditToken via browser and retry
 */
export async function loginToHostaway(email: string, password: string): Promise<LoginResult> {
  try {
    // Step 1: Solve reCAPTCHA
    const captchaToken = await solveCaptcha();

    // Step 2: Try login without auditToken
    console.log('[HostawayLogin] Attempting login without auditToken...');
    let result = await attemptLogin(email, password, captchaToken, '');

    console.log(`[HostawayLogin] Response: ${result.status} — ${JSON.stringify(result.data).substring(0, 200)}`);

    // If captcha is rejected, the token might need auditToken too
    if (result.status === 403 && result.data?.message?.toLowerCase().includes('captcha')) {
      console.log('[HostawayLogin] Login rejected — trying with auditToken...');
      const auditToken = await extractAuditToken();

      // Need a fresh captcha token (old one is single-use)
      const freshCaptchaToken = await solveCaptcha();
      result = await attemptLogin(email, password, freshCaptchaToken, auditToken);
      console.log(`[HostawayLogin] Response with auditToken: ${result.status} — ${JSON.stringify(result.data).substring(0, 200)}`);
    }

    // Handle responses
    if (result.status === 200) {
      // Success — extract JWT from response
      const jwt = extractJwtFromResponse(result.data);
      if (jwt) {
        const payload = decodeJwtPayload(jwt);
        console.log(`[HostawayLogin] Login successful for ${email}`);
        return {
          success: true,
          jwt,
          userEmail: payload?.userEmail || email,
          accountId: payload?.accountId?.toString(),
        };
      }
      // 200 but no JWT — might be stored differently
      console.log('[HostawayLogin] 200 response but no JWT found in body:', JSON.stringify(result.data).substring(0, 500));
      return { success: false, error: 'Login succeeded but token format unexpected. Check logs.' };
    }

    if (result.status === 403) {
      const msg = result.data?.message || 'Login failed';
      if (msg.toLowerCase().includes('2fa') || msg.toLowerCase().includes('verify') || msg.toLowerCase().includes('email')) {
        // 2FA required — store session for retry
        const sessionId = crypto.randomUUID();
        const timeout = setTimeout(() => cleanupSession(sessionId), 180_000);
        pendingSessions.set(sessionId, { email, password, captchaToken: '', auditToken: '', createdAt: Date.now(), timeout });
        console.log(`[HostawayLogin] 2FA required for ${email}, session: ${sessionId}`);
        return { success: true, pending2fa: true, sessionId };
      }
      if (msg.toLowerCase().includes('invalid') || msg.toLowerCase().includes('wrong') || msg.toLowerCase().includes('incorrect')) {
        return { success: false, error: 'Invalid email or password' };
      }
      return { success: false, error: msg };
    }

    return { success: false, error: result.data?.message || `Login failed with status ${result.status}` };
  } catch (err: any) {
    console.error('[HostawayLogin] Login failed:', err.message);
    return { success: false, error: err.message || 'Login failed' };
  }
}

/**
 * Complete 2FA — user clicked the email link, retry login.
 */
export async function verify2fa(sessionId: string): Promise<LoginResult> {
  const session = pendingSessions.get(sessionId);
  if (!session) {
    return { success: false, error: 'Session expired. Please try logging in again.' };
  }

  try {
    // Need fresh captcha for retry
    const captchaToken = await solveCaptcha();
    const result = await attemptLogin(session.email, session.password, captchaToken, session.auditToken);

    if (result.status === 200) {
      const jwt = extractJwtFromResponse(result.data);
      cleanupSession(sessionId);
      if (jwt) {
        const payload = decodeJwtPayload(jwt);
        console.log(`[HostawayLogin] 2FA verified for ${session.email}`);
        return {
          success: true,
          jwt,
          userEmail: payload?.userEmail || session.email,
          accountId: payload?.accountId?.toString(),
        };
      }
      return { success: false, error: 'Login succeeded but token not found in response.' };
    }

    if (result.status === 403) {
      return { success: false, error: 'Email verification not completed yet. Click the link in your email and try again.' };
    }

    cleanupSession(sessionId);
    return { success: false, error: result.data?.message || 'Verification failed' };
  } catch (err: any) {
    console.error('[HostawayLogin] 2FA verification failed:', err.message);
    cleanupSession(sessionId);
    return { success: false, error: err.message || 'Verification failed' };
  }
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function extractJwtFromResponse(data: any): string | null {
  // Try common response shapes
  if (typeof data === 'string' && data.startsWith('eyJ')) return data;
  if (data?.jwt) return data.jwt;
  if (data?.token) return data.token;
  if (data?.result?.jwt) return data.result.jwt;
  if (data?.result?.token) return data.result.token;
  if (data?.data?.jwt) return data.data.jwt;
  if (data?.accessToken) return data.accessToken;

  // Search for JWT pattern in stringified response
  const str = JSON.stringify(data);
  const match = str.match(/"(eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+)"/);
  if (match) return match[1];

  return null;
}

function decodeJwtPayload(jwt: string): any {
  try {
    const parts = jwt.split('.');
    if (parts.length !== 3) return null;
    return JSON.parse(Buffer.from(parts[1], 'base64url').toString('utf8'));
  } catch {
    return null;
  }
}
